image: Visual Studio 2019
platform: x64
configuration: Release
clone_folder: C:\Projects\TweedeFrameworkRedux

before_build:
- cmd: |-
    mkdir Build
    cd Build
    cmake --version
    cmake .. -G %generator%
    cmake --build