image: Visual Studio 2019
platform: x64
configuration: Release
clone_folder: C:\Projects\TweedeFrameworkRedux

build:
- cmd: |-
    mkdir Build
    cd Build
    cmake --version
    cmake .. -G "Visual Studio 16 2019"
    cmake --build